### ISSUE TITLE
Build a Runnable Jar

### ISSUE THREAD

**Issue by joel7fold** [aslamanver/jar-builder#5]
hello, how can i build a runnable jar using this extension in vs code?

**Comment by javatlacati** [comment]
By adding a manifest, please check [the Java Tutorial ](https://docs.oracle.com/javase/tutorial/deployment/jar/appman.html)regarding that matter.

**Comment by aslamanver** [comment]
This is because of the MANIFEST.MF file was not there, you can refer the below link to get the runnable Jar file, this is not the part of the Jar conversation.


https://stackoverflow.com/questions/9689793/cant-execute-jar-file-no-main-manifest-attribute
