### ISSUE TITLE
Invalid flag error

### ISSUE THREAD

**Issue by xinaras** [aslamanver/jar-builder#7]
I'm trying to build a .jar file but all I get is a flag error with the adress of my project's resources folder. It's a simple program: a few classes and some .png images (more precisely, a simple Russian Checkers game). I have everything properly setted up for Java developing (JDK, JRE, my PATH variables... everything related to Java works fine for me except this extension). If I could get an answer, it'd be awesome since this VSCode extension seems to be pretty nice. I attach a screenshot of the invalid flag error I'm getting.

Thanks in advance. Greetings from Argentina.
![invalid flag error](https://user-images.githubusercontent.com/66426042/85817112-7dd4a080-b743-11ea-8dcb-0e18fa59c032.JPG)

**Comment by aslamanver** [comment]
Thank you for using this, and I can help you in a better way, could you please try the GIT Bash for your VSCode terminal and try again.
